// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';
import {openai} from '../models';

export function GetCurrentUser():Promise<spotify.UserProfile>;

export function GetInitialSuggestionState():Promise<boolean>;

export function GetSavedTracks(arg1:number,arg2:number):Promise<spotify.SavedTracks>;

export function GetSpotifyApp():Promise<spotify.App>;

export function ProcessLibraryAndGetFirstSuggestion():Promise<openai.Message>;

export function ProvideSuggestionFeedback(arg1:string):Promise<void>;

export function RemoveTrack(arg1:string):Promise<void>;

export function RequestNewSuggestion():Promise<openai.Message>;

export function SaveTrack(arg1:string):Promise<void>;

export function SearchTracks(arg1:string,arg2:number):Promise<Array<spotify.SimpleTrack>>;

export function SetSpotifyClient(arg1:spotify.Client):Promise<void>;
