// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';

export function GetCurrentUser():Promise<spotify.UserProfile>;

export function GetSavedTracks(arg1:number,arg2:number):Promise<spotify.SavedTracks>;

export function RemoveTrack(arg1:string):Promise<void>;

export function SaveTrack(arg1:string):Promise<void>;

export function SearchTracks(arg1:string,arg2:number):Promise<Array<spotify.SimpleTrack>>;

export function SetSpotifyClient(arg1:spotify.Client):Promise<void>;
