// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSpotifyCredentials() {
  return window['go']['spotify']['WailsClient']['ClearSpotifyCredentials']();
}

export function GetAuthStatus() {
  return window['go']['spotify']['WailsClient']['GetAuthStatus']();
}

export function GetCurrentUser() {
  return window['go']['spotify']['WailsClient']['GetCurrentUser']();
}

export function GetInitialSuggestionState() {
  return window['go']['spotify']['WailsClient']['GetInitialSuggestionState']();
}

export function GetSavedTracks(arg1, arg2) {
  return window['go']['spotify']['WailsClient']['GetSavedTracks'](arg1, arg2);
}

export function GetSpotifyApp() {
  return window['go']['spotify']['WailsClient']['GetSpotifyApp']();
}

export function GetValidToken() {
  return window['go']['spotify']['WailsClient']['GetValidToken']();
}

export function PausePlaybackOnDevice(arg1) {
  return window['go']['spotify']['WailsClient']['PausePlaybackOnDevice'](arg1);
}

export function PlayTrackOnDevice(arg1, arg2) {
  return window['go']['spotify']['WailsClient']['PlayTrackOnDevice'](arg1, arg2);
}

export function ProcessLibraryAndGetFirstSuggestion() {
  return window['go']['spotify']['WailsClient']['ProcessLibraryAndGetFirstSuggestion']();
}

export function ProvideSuggestionFeedback(arg1) {
  return window['go']['spotify']['WailsClient']['ProvideSuggestionFeedback'](arg1);
}

export function RemoveTrack(arg1) {
  return window['go']['spotify']['WailsClient']['RemoveTrack'](arg1);
}

export function RequestNewSuggestion() {
  return window['go']['spotify']['WailsClient']['RequestNewSuggestion']();
}

export function SaveTrack(arg1) {
  return window['go']['spotify']['WailsClient']['SaveTrack'](arg1);
}

export function SearchTracks(arg1, arg2) {
  return window['go']['spotify']['WailsClient']['SearchTracks'](arg1, arg2);
}

export function SetSpotifyClient(arg1) {
  return window['go']['spotify']['WailsClient']['SetSpotifyClient'](arg1);
}

export function WailsInit() {
  return window['go']['spotify']['WailsClient']['WailsInit']();
}

export function WailsShutdown() {
  return window['go']['spotify']['WailsClient']['WailsShutdown']();
}
