// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['spotify']['WailsClient']['GetCurrentUser']();
}

export function GetSavedTracks(arg1, arg2) {
  return window['go']['spotify']['WailsClient']['GetSavedTracks'](arg1, arg2);
}

export function RemoveTrack(arg1) {
  return window['go']['spotify']['WailsClient']['RemoveTrack'](arg1);
}

export function SaveTrack(arg1) {
  return window['go']['spotify']['WailsClient']['SaveTrack'](arg1);
}

export function SearchTracks(arg1, arg2) {
  return window['go']['spotify']['WailsClient']['SearchTracks'](arg1, arg2);
}

export function SetSpotifyClient(arg1) {
  return window['go']['spotify']['WailsClient']['SetSpotifyClient'](arg1);
}
