// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';

export function ClearSpotifyCredentials():Promise<void>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetCurrentUser():Promise<spotify.UserProfile>;

export function GetInitialSuggestionState():Promise<boolean>;

export function GetSavedTracks(arg1:number,arg2:number):Promise<spotify.SavedTracks>;

export function GetSpotifyApp():Promise<spotify.App>;

export function GetValidToken():Promise<string>;

export function PausePlaybackOnDevice(arg1:string):Promise<void>;

export function PlayTrackOnDevice(arg1:string,arg2:string):Promise<void>;

export function ProcessLibraryAndGetFirstSuggestion():Promise<spotify.SuggestedTrackInfo>;

export function ProvideSuggestionFeedback(arg1:string):Promise<void>;

export function RemoveTrack(arg1:string):Promise<void>;

export function RequestNewSuggestion():Promise<spotify.SuggestedTrackInfo>;

export function SaveTrack(arg1:string):Promise<void>;

export function SearchTracks(arg1:string,arg2:number):Promise<Array<spotify.SimpleTrack>>;

export function SetSpotifyClient(arg1:spotify.Client):Promise<void>;

export function WailsInit():Promise<void>;

export function WailsShutdown():Promise<void>;
