// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearOpenAIToken() {
  return window['go']['bindings']['Auth']['ClearOpenAIToken']();
}

export function GetOpenAIToken() {
  return window['go']['bindings']['Auth']['GetOpenAIToken']();
}

export function SaveOpenAIToken(arg1) {
  return window['go']['bindings']['Auth']['SaveOpenAIToken'](arg1);
}
