// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearOpenAIToken():Promise<void>;

export function ClearTMBDAccessToken():Promise<void>;

export function GetOpenAIToken():Promise<string>;

export function GetTMBDAccessToken():Promise<string>;

export function SaveOpenAIToken(arg1:string):Promise<void>;

export function SaveTMBDAccessToken(arg1:string):Promise<void>;
