// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToReadList(arg1) {
  return window['go']['bindings']['Books']['AddToReadList'](arg1);
}

export function GetBookDetails(arg1) {
  return window['go']['bindings']['Books']['GetBookDetails'](arg1);
}

export function GetBookSuggestion() {
  return window['go']['bindings']['Books']['GetBookSuggestion']();
}

export function GetFavoriteBooks() {
  return window['go']['bindings']['Books']['GetFavoriteBooks']();
}

export function GetReadList() {
  return window['go']['bindings']['Books']['GetReadList']();
}

export function ProvideSuggestionFeedback(arg1, arg2, arg3) {
  return window['go']['bindings']['Books']['ProvideSuggestionFeedback'](arg1, arg2, arg3);
}

export function RemoveFromReadList(arg1, arg2) {
  return window['go']['bindings']['Books']['RemoveFromReadList'](arg1, arg2);
}

export function SearchBooks(arg1) {
  return window['go']['bindings']['Books']['SearchBooks'](arg1);
}

export function SetFavoriteBooks(arg1) {
  return window['go']['bindings']['Books']['SetFavoriteBooks'](arg1);
}
