// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {bindings} from '../models';

export function AddToReadList(arg1:session.Book):Promise<void>;

export function GetBookDetails(arg1:string):Promise<bindings.BookWithSavedStatus>;

export function GetBookSuggestion():Promise<Record<string, any>>;

export function GetFavoriteBooks():Promise<Array<session.Book>>;

export function GetReadList():Promise<Array<session.Book>>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:string,arg3:string):Promise<void>;

export function RemoveFromReadList(arg1:string,arg2:string):Promise<void>;

export function SearchBooks(arg1:string):Promise<Array<bindings.BookWithSavedStatus>>;

export function SetFavoriteBooks(arg1:Array<session.Book>):Promise<void>;
