// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rawg} from '../models';
import {session} from '../models';
import {bindings} from '../models';

export function AddGameToWatchlist(arg1:number):Promise<void>;

export function ConvertToSimpleGames(arg1:Array<rawg.Game>):Promise<Array<rawg.SimpleGame>>;

export function GetFavoriteGames():Promise<Array<session.VideoGame>>;

export function GetGameDetails(arg1:number):Promise<bindings.GameWithSavedStatus>;

export function GetGameSuggestion():Promise<Record<string, any>>;

export function GetGames(arg1:number,arg2:number):Promise<rawg.GameSearchResponse>;

export function GetSavedGames():Promise<Array<bindings.GameWithSavedStatus>>;

export function GetWatchlistGames():Promise<Array<bindings.GameWithSavedStatus>>;

export function HasValidCredentials():Promise<boolean>;

export function IsGameInWatchlist(arg1:number):Promise<boolean>;

export function IsGameSaved(arg1:number):Promise<boolean>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:number):Promise<void>;

export function RefreshCredentials():Promise<boolean>;

export function RemoveGameFromWatchlist(arg1:number):Promise<void>;

export function SaveGame(arg1:number):Promise<void>;

export function SearchGames(arg1:string,arg2:number,arg3:number):Promise<rawg.GameSearchResponse>;

export function SetFavoriteGames(arg1:Array<session.VideoGame>):Promise<void>;

export function ToSimpleGame(arg1:rawg.Game):Promise<rawg.SimpleGame>;

export function UnsaveGame(arg1:number):Promise<void>;
