// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {bindings} from '../models';

export function AddToWatchlist(arg1:session.VideoGame):Promise<void>;

export function GetFavoriteGames():Promise<Array<session.VideoGame>>;

export function GetGameDetails(arg1:number):Promise<bindings.GameWithSavedStatus>;

export function GetGameSuggestion():Promise<Record<string, any>>;

export function GetWatchlist():Promise<Array<session.VideoGame>>;

export function HasValidCredentials():Promise<boolean>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:number):Promise<void>;

export function RefreshCredentials():Promise<boolean>;

export function RefreshLLMClients():Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function SearchGames(arg1:string):Promise<Array<bindings.GameWithSavedStatus>>;

export function SetFavoriteGames(arg1:Array<session.VideoGame>):Promise<void>;
