// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToWatchlist(arg1) {
  return window['go']['bindings']['Games']['AddGameToWatchlist'](arg1);
}

export function ConvertToSimpleGames(arg1) {
  return window['go']['bindings']['Games']['ConvertToSimpleGames'](arg1);
}

export function GetFavoriteGames() {
  return window['go']['bindings']['Games']['GetFavoriteGames']();
}

export function GetGameDetails(arg1) {
  return window['go']['bindings']['Games']['GetGameDetails'](arg1);
}

export function GetGameSuggestion() {
  return window['go']['bindings']['Games']['GetGameSuggestion']();
}

export function GetGames(arg1, arg2) {
  return window['go']['bindings']['Games']['GetGames'](arg1, arg2);
}

export function GetSavedGames() {
  return window['go']['bindings']['Games']['GetSavedGames']();
}

export function GetWatchlistGames() {
  return window['go']['bindings']['Games']['GetWatchlistGames']();
}

export function HasValidCredentials() {
  return window['go']['bindings']['Games']['HasValidCredentials']();
}

export function IsGameInWatchlist(arg1) {
  return window['go']['bindings']['Games']['IsGameInWatchlist'](arg1);
}

export function IsGameSaved(arg1) {
  return window['go']['bindings']['Games']['IsGameSaved'](arg1);
}

export function ProvideSuggestionFeedback(arg1, arg2) {
  return window['go']['bindings']['Games']['ProvideSuggestionFeedback'](arg1, arg2);
}

export function RefreshCredentials() {
  return window['go']['bindings']['Games']['RefreshCredentials']();
}

export function RemoveGameFromWatchlist(arg1) {
  return window['go']['bindings']['Games']['RemoveGameFromWatchlist'](arg1);
}

export function SaveGame(arg1) {
  return window['go']['bindings']['Games']['SaveGame'](arg1);
}

export function SearchGames(arg1, arg2, arg3) {
  return window['go']['bindings']['Games']['SearchGames'](arg1, arg2, arg3);
}

export function SetFavoriteGames(arg1) {
  return window['go']['bindings']['Games']['SetFavoriteGames'](arg1);
}

export function ToSimpleGame(arg1) {
  return window['go']['bindings']['Games']['ToSimpleGame'](arg1);
}

export function UnsaveGame(arg1) {
  return window['go']['bindings']['Games']['UnsaveGame'](arg1);
}
