// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToWatchlist(arg1) {
  return window['go']['bindings']['Games']['AddToWatchlist'](arg1);
}

export function GetFavoriteGames() {
  return window['go']['bindings']['Games']['GetFavoriteGames']();
}

export function GetGameDetails(arg1) {
  return window['go']['bindings']['Games']['GetGameDetails'](arg1);
}

export function GetGameSuggestion() {
  return window['go']['bindings']['Games']['GetGameSuggestion']();
}

export function GetWatchlist() {
  return window['go']['bindings']['Games']['GetWatchlist']();
}

export function HasValidCredentials() {
  return window['go']['bindings']['Games']['HasValidCredentials']();
}

export function ProvideSuggestionFeedback(arg1, arg2) {
  return window['go']['bindings']['Games']['ProvideSuggestionFeedback'](arg1, arg2);
}

export function RefreshCredentials() {
  return window['go']['bindings']['Games']['RefreshCredentials']();
}

export function RefreshLLMClients() {
  return window['go']['bindings']['Games']['RefreshLLMClients']();
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['bindings']['Games']['RemoveFromWatchlist'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['bindings']['Games']['SearchGames'](arg1);
}

export function SetFavoriteGames(arg1) {
  return window['go']['bindings']['Games']['SetFavoriteGames'](arg1);
}
