// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitialMovies() {
  return window['go']['bindings']['Movies']['GetInitialMovies']();
}

export function GetMovieDetails(arg1) {
  return window['go']['bindings']['Movies']['GetMovieDetails'](arg1);
}

export function SearchMovies(arg1) {
  return window['go']['bindings']['Movies']['SearchMovies'](arg1);
}

export function SetInitialMovies(arg1) {
  return window['go']['bindings']['Movies']['SetInitialMovies'](arg1);
}
