// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFavoriteMovies() {
  return window['go']['bindings']['Movies']['GetFavoriteMovies']();
}

export function GetMovieDetails(arg1) {
  return window['go']['bindings']['Movies']['GetMovieDetails'](arg1);
}

export function GetMovieSuggestion() {
  return window['go']['bindings']['Movies']['GetMovieSuggestion']();
}

export function HasValidCredentials() {
  return window['go']['bindings']['Movies']['HasValidCredentials']();
}

export function ProvideSuggestionFeedback(arg1, arg2) {
  return window['go']['bindings']['Movies']['ProvideSuggestionFeedback'](arg1, arg2);
}

export function RefreshCredentials() {
  return window['go']['bindings']['Movies']['RefreshCredentials']();
}

export function SearchMovies(arg1) {
  return window['go']['bindings']['Movies']['SearchMovies'](arg1);
}

export function SetFavoriteMovies(arg1) {
  return window['go']['bindings']['Movies']['SetFavoriteMovies'](arg1);
}
