// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {bindings} from '../models';

export function AddToWatchlist(arg1:session.Movie):Promise<void>;

export function GetFavoriteMovies():Promise<Array<session.Movie>>;

export function GetMovieDetails(arg1:number):Promise<bindings.MovieWithSavedStatus>;

export function GetMovieSuggestion():Promise<Record<string, any>>;

export function GetWatchlist():Promise<Array<session.Movie>>;

export function HasValidCredentials():Promise<boolean>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:number):Promise<void>;

export function RefreshCredentials():Promise<boolean>;

export function RefreshLLMClients():Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function SearchMovies(arg1:string):Promise<Array<bindings.MovieWithSavedStatus>>;

export function SetFavoriteMovies(arg1:Array<session.Movie>):Promise<void>;
