// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function GetInitialMovies():Promise<Record<string, bindings.Movie>>;

export function GetMovieDetails(arg1:number):Promise<bindings.MovieWithSavedStatus>;

export function SearchMovies(arg1:string):Promise<Array<bindings.MovieWithSavedStatus>>;

export function SetInitialMovies(arg1:Record<string, bindings.Movie>):Promise<void>;
