// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';
import {session} from '../models';

export function ClearSpotifyCredentials():Promise<void>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetCurrentUser():Promise<spotify.UserProfile>;

export function GetSavedTracks(arg1:number,arg2:number):Promise<spotify.SavedTracks>;

export function GetValidToken():Promise<string>;

export function PausePlaybackOnDevice(arg1:string):Promise<void>;

export function PlayTrackOnDevice(arg1:string,arg2:string):Promise<void>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RemoveTrack(arg1:string):Promise<void>;

export function RequestNewSuggestion():Promise<spotify.SuggestedTrackInfo>;

export function SaveTrack(arg1:string):Promise<void>;

export function SearchTracks(arg1:string,arg2:number):Promise<Array<spotify.SimpleTrack>>;

export function SetSpotifyClient(arg1:spotify.Client):Promise<void>;
