// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSpotifyCredentials() {
  return window['go']['bindings']['Music']['ClearSpotifyCredentials']();
}

export function GetAuthStatus() {
  return window['go']['bindings']['Music']['GetAuthStatus']();
}

export function GetCurrentUser() {
  return window['go']['bindings']['Music']['GetCurrentUser']();
}

export function GetSavedTracks(arg1, arg2) {
  return window['go']['bindings']['Music']['GetSavedTracks'](arg1, arg2);
}

export function GetValidToken() {
  return window['go']['bindings']['Music']['GetValidToken']();
}

export function PausePlaybackOnDevice(arg1) {
  return window['go']['bindings']['Music']['PausePlaybackOnDevice'](arg1);
}

export function PlayTrackOnDevice(arg1, arg2) {
  return window['go']['bindings']['Music']['PlayTrackOnDevice'](arg1, arg2);
}

export function ProvideSuggestionFeedback(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['Music']['ProvideSuggestionFeedback'](arg1, arg2, arg3, arg4);
}

export function RemoveTrack(arg1) {
  return window['go']['bindings']['Music']['RemoveTrack'](arg1);
}

export function RequestNewSuggestion() {
  return window['go']['bindings']['Music']['RequestNewSuggestion']();
}

export function SaveTrack(arg1) {
  return window['go']['bindings']['Music']['SaveTrack'](arg1);
}

export function SearchTracks(arg1, arg2) {
  return window['go']['bindings']['Music']['SearchTracks'](arg1, arg2);
}

export function SetSpotifyClient(arg1) {
  return window['go']['bindings']['Music']['SetSpotifyClient'](arg1);
}
