// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContinuousPlayback():Promise<boolean>;

export function SetContinuousPlayback(arg1:boolean):Promise<void>;
