// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatGPTModel():Promise<string>;

export function GetContinuousPlayback():Promise<boolean>;

export function GetGeminiModel():Promise<string>;

export function GetLLMProvider():Promise<string>;

export function SetChatGPTModel(arg1:string):Promise<void>;

export function SetContinuousPlayback(arg1:boolean):Promise<void>;

export function SetGeminiModel(arg1:string):Promise<void>;

export function SetLLMProvider(arg1:string):Promise<void>;
