// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChatGPTModel() {
  return window['go']['bindings']['Settings']['GetChatGPTModel']();
}

export function GetContinuousPlayback() {
  return window['go']['bindings']['Settings']['GetContinuousPlayback']();
}

export function GetGeminiModel() {
  return window['go']['bindings']['Settings']['GetGeminiModel']();
}

export function GetLLMProvider() {
  return window['go']['bindings']['Settings']['GetLLMProvider']();
}

export function SetChatGPTModel(arg1) {
  return window['go']['bindings']['Settings']['SetChatGPTModel'](arg1);
}

export function SetContinuousPlayback(arg1) {
  return window['go']['bindings']['Settings']['SetContinuousPlayback'](arg1);
}

export function SetGeminiModel(arg1) {
  return window['go']['bindings']['Settings']['SetGeminiModel'](arg1);
}

export function SetLLMProvider(arg1) {
  return window['go']['bindings']['Settings']['SetLLMProvider'](arg1);
}
