// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToWatchlist(arg1) {
  return window['go']['bindings']['TVShows']['AddToWatchlist'](arg1);
}

export function GetFavoriteTVShows() {
  return window['go']['bindings']['TVShows']['GetFavoriteTVShows']();
}

export function GetTVShowDetails(arg1) {
  return window['go']['bindings']['TVShows']['GetTVShowDetails'](arg1);
}

export function GetTVShowSuggestion() {
  return window['go']['bindings']['TVShows']['GetTVShowSuggestion']();
}

export function GetWatchlist() {
  return window['go']['bindings']['TVShows']['GetWatchlist']();
}

export function HasValidCredentials() {
  return window['go']['bindings']['TVShows']['HasValidCredentials']();
}

export function ProvideSuggestionFeedback(arg1, arg2) {
  return window['go']['bindings']['TVShows']['ProvideSuggestionFeedback'](arg1, arg2);
}

export function RefreshCredentials() {
  return window['go']['bindings']['TVShows']['RefreshCredentials']();
}

export function RefreshLLMClients() {
  return window['go']['bindings']['TVShows']['RefreshLLMClients']();
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['bindings']['TVShows']['RemoveFromWatchlist'](arg1);
}

export function SearchTVShows(arg1) {
  return window['go']['bindings']['TVShows']['SearchTVShows'](arg1);
}

export function SetFavoriteTVShows(arg1) {
  return window['go']['bindings']['TVShows']['SetFavoriteTVShows'](arg1);
}
