// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {bindings} from '../models';

export function AddToWatchlist(arg1:session.TVShow):Promise<void>;

export function GetFavoriteTVShows():Promise<Array<session.TVShow>>;

export function GetTVShowDetails(arg1:number):Promise<bindings.TVShowWithSavedStatus>;

export function GetTVShowSuggestion():Promise<Record<string, any>>;

export function GetWatchlist():Promise<Array<session.TVShow>>;

export function HasValidCredentials():Promise<boolean>;

export function ProvideSuggestionFeedback(arg1:session.Outcome,arg2:number):Promise<void>;

export function RefreshCredentials():Promise<boolean>;

export function RefreshLLMClients():Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function SearchTVShows(arg1:string):Promise<Array<bindings.TVShowWithSavedStatus>>;

export function SetFavoriteTVShows(arg1:Array<session.TVShow>):Promise<void>;
