/// Database Queries for Interestnaut
/// 
/// This file contains all SQL queries used by the SQLite database.
/// The database uses a normalized schema with these main tables:
/// - media_items: Central table for all media content
/// - recommendations: Suggestions generated by the system
/// - favorites: User's favorite items (both recommended and user-added)
/// - watchlist: User's watchlist items (both recommended and user-added)
/// - media_metadata: Flexible key-value storage for media properties
/// - user_constraints: User-defined search constraints

/// Static Data Tables

// Create media types table with predefined values
const String createMediaTypesTableQuery = '''
CREATE TABLE IF NOT EXISTS media_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);
''';

const String insertMediaTypesQuery = '''
  INSERT OR IGNORE INTO media_types (name) VALUES 
    ('music'), ('movie'), ('tv_show'), ('video_game'), ('book');
''';

// Create recommendation status table with predefined values
const String createRecommendationStatusTableQuery = '''
CREATE TABLE IF NOT EXISTS recommendation_status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);
''';

const String insertRecommendationStatusQuery = '''
  INSERT OR IGNORE INTO recommendation_status (name) VALUES 
    ('pending'), ('liked'), ('disliked'), ('skipped'), ('added'), ('watchlist');
''';

/// Core Tables

// Create media items table (central table for all media content)
const String createMediaItemsTableQuery = '''
CREATE TABLE IF NOT EXISTS media_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_type_id INTEGER NOT NULL,
  vector_media_id TEXT NOT NULL,
  title TEXT NOT NULL,
  primary_creator TEXT,
  cover_art_url TEXT,
  description TEXT,
  wiki_url TEXT,
  wikidata_id TEXT,
  themes TEXT,
  genres TEXT,
  youtube_id TEXT,
  spotify_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (media_type_id) REFERENCES media_types (id),
  UNIQUE(media_type_id, title, primary_creator)
);

CREATE INDEX IF NOT EXISTS idx_media_items_type ON media_items(media_type_id);
CREATE INDEX IF NOT EXISTS idx_media_items_title ON media_items(title);
CREATE INDEX IF NOT EXISTS idx_media_items_creator ON media_items(primary_creator);
CREATE INDEX IF NOT EXISTS idx_media_items_vector_id ON media_items(vector_media_id);
''';

// Create recommendations table
const String createRecommendationsTableQuery = '''
CREATE TABLE IF NOT EXISTS recommendations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_item_id INTEGER NOT NULL,
  query TEXT NOT NULL,
  bot_reasoning TEXT,
  status_id INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT,
  FOREIGN KEY (media_item_id) REFERENCES media_items (id),
  FOREIGN KEY (status_id) REFERENCES recommendation_status (id),
  UNIQUE(media_item_id)
);

CREATE INDEX IF NOT EXISTS idx_recommendations_media_item ON recommendations(media_item_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_status ON recommendations(status_id);
''';

// Create favorites table (simplified - no recommendation_id needed)
const String createFavoritesTableQuery = '''
CREATE TABLE IF NOT EXISTS favorites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_item_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (media_item_id) REFERENCES media_items (id),
  UNIQUE(media_item_id)
);

CREATE INDEX IF NOT EXISTS idx_favorites_media_item ON favorites(media_item_id);
''';

// Create watchlist table (simplified - no recommendation_id needed)
const String createWatchlistTableQuery = '''
CREATE TABLE IF NOT EXISTS watchlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_item_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (media_item_id) REFERENCES media_items (id),
  UNIQUE(media_item_id)
);

CREATE INDEX IF NOT EXISTS idx_watchlist_media_item ON watchlist(media_item_id);
''';

// Create media metadata table for flexible key-value storage
const String createMediaMetadataTableQuery = '''
CREATE TABLE IF NOT EXISTS media_metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_item_id INTEGER NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  FOREIGN KEY (media_item_id) REFERENCES media_items (id),
  UNIQUE(media_item_id, key)
);

CREATE INDEX IF NOT EXISTS idx_media_metadata_key ON media_metadata(key);
''';

// Create media blends table
const String createMediaBlendsTableQuery = '''
CREATE TABLE IF NOT EXISTS media_blends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  primary_media_type_id INTEGER NOT NULL,
  blended_media_type_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (primary_media_type_id) REFERENCES media_types (id),
  FOREIGN KEY (blended_media_type_id) REFERENCES media_types (id),
  UNIQUE(primary_media_type_id, blended_media_type_id)
);

CREATE INDEX IF NOT EXISTS idx_media_blends_primary ON media_blends(primary_media_type_id);
''';

// Create media matching table
const String createMediaMatchingTableQuery = '''
CREATE TABLE IF NOT EXISTS media_matching (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_type_id INTEGER NOT NULL,
  value TEXT NOT NULL,
  is_positive BOOLEAN NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (media_type_id) REFERENCES media_types (id),
  UNIQUE(media_type_id, value)
);

CREATE INDEX IF NOT EXISTS idx_media_matching_type ON media_matching(media_type_id);
''';

// Create media priority titles table
const String createMediaPriorityTitlesTableQuery = '''
CREATE TABLE IF NOT EXISTS media_priority_titles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_type_id INTEGER NOT NULL,
  media_item_id INTEGER NOT NULL,
  is_positive BOOLEAN NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (media_type_id) REFERENCES media_types (id),
  FOREIGN KEY (media_item_id) REFERENCES media_items (id),
  UNIQUE(media_type_id, media_item_id)
);

CREATE INDEX IF NOT EXISTS idx_media_priority_titles_type ON media_priority_titles(media_type_id);
''';

// Create media settings table
const String createMediaSettingsTableQuery = '''
CREATE TABLE IF NOT EXISTS media_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_type_id INTEGER NOT NULL,
  similarity_matching REAL NOT NULL DEFAULT 0.5,
  themes_matching INTEGER NOT NULL DEFAULT 3,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (media_type_id) REFERENCES media_types (id),
  UNIQUE(media_type_id)
);

CREATE INDEX IF NOT EXISTS idx_media_settings_type ON media_settings(media_type_id);
''';

// Create general settings table for app-wide and media-specific settings
const String createGeneralSettingsTableQuery = '''
CREATE TABLE IF NOT EXISTS general_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_general_settings_key ON general_settings(key);
''';

/// Media Type Queries

// Get media type ID by name
const String getMediaTypeIdQuery = '''
SELECT id FROM media_types WHERE name = ?;
''';

// Get all media types
const String getAllMediaTypesQuery = '''
SELECT id, name FROM media_types ORDER BY name;
''';

/// Media Settings Queries

// Insert or update media settings
const String insertOrUpdateMediaSettingsQuery = '''
INSERT OR REPLACE INTO media_settings (media_type_id, similarity_matching, themes_matching, created_at, updated_at)
VALUES (?, ?, ?, ?, ?);
''';

// Get media settings for a media type
const String getMediaSettingsQuery = '''
SELECT ms.similarity_matching, ms.themes_matching, ms.created_at, ms.updated_at
FROM media_settings ms
JOIN media_types mt ON ms.media_type_id = mt.id
WHERE mt.name = ?;
''';

/// General Settings Queries

// Insert or update general setting
const String insertOrUpdateGeneralSettingQuery = '''
INSERT OR REPLACE INTO general_settings (key, value, created_at, updated_at)
VALUES (?, ?, ?, ?);
''';

// Get general setting by key
const String getGeneralSettingQuery = '''
SELECT value FROM general_settings WHERE key = ?;
''';

// Get all general settings
const String getAllGeneralSettingsQuery = '''
SELECT key, value FROM general_settings;
''';

/// Media Matching Queries

// Insert media matching constraint
const String insertMediaMatchingQuery = '''
INSERT OR REPLACE INTO media_matching (media_type_id, value, is_positive, created_at)
VALUES (?, ?, ?, ?);
''';

// Get media matching constraints for a media type
const String getMediaMatchingQuery = '''
SELECT mm.value, mm.is_positive
FROM media_matching mm
JOIN media_types mt ON mm.media_type_id = mt.id
WHERE mt.name = ?;
''';

// Delete media matching constraint
const String deleteMediaMatchingQuery = '''
DELETE FROM media_matching WHERE media_type_id = ? AND value = ?;
''';

/// Media Priority Titles Queries

// Insert media priority title
const String insertMediaPriorityTitleQuery = '''
INSERT OR REPLACE INTO media_priority_titles (media_type_id, media_item_id, is_positive, created_at)
VALUES (?, ?, ?, ?);
''';

// Get media priority titles for a media type
const String getMediaPriorityTitlesQuery = '''
SELECT mi.title, mi.primary_creator, mpt.is_positive, mpt.created_at
FROM media_priority_titles mpt
JOIN media_types mt ON mpt.media_type_id = mt.id
JOIN media_items mi ON mpt.media_item_id = mi.id
WHERE mt.name = ?;
''';

// Delete media priority title
const String deleteMediaPriorityTitleQuery = '''
DELETE FROM media_priority_titles WHERE media_type_id = ? AND media_item_id = ?;
''';

/// Media Blends Queries

// Insert media blend
const String insertMediaBlendQuery = '''
INSERT OR IGNORE INTO media_blends (primary_media_type_id, blended_media_type_id, created_at)
VALUES (?, ?, ?);
''';

// Get media blends for a media type
const String getMediaBlendsQuery = '''
SELECT mt_blended.name as blended_media_type
FROM media_blends mb
JOIN media_types mt_primary ON mb.primary_media_type_id = mt_primary.id
JOIN media_types mt_blended ON mb.blended_media_type_id = mt_blended.id
WHERE mt_primary.name = ?;
''';

// Delete media blend
const String deleteMediaBlendQuery = '''
DELETE FROM media_blends WHERE primary_media_type_id = ? AND blended_media_type_id = ?;
''';

/// Media Items Queries

// Insert or get existing media item
const String insertOrGetMediaItemQuery = '''
INSERT OR IGNORE INTO media_items (
  media_type_id, vector_media_id, title, primary_creator, cover_art_url, 
  description, wiki_url, wikidata_id, themes, genres, youtube_id, spotify_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
''';

// Get media item by title and creator
const String getMediaItemByTitleCreatorQuery = '''
SELECT mi.id 
FROM media_items mi
JOIN media_types mt ON mi.media_type_id = mt.id
WHERE mi.title = ? AND COALESCE(mi.primary_creator, '') = ? AND mt.name = ?;
''';

// Get media item by ID
const String getMediaItemByIdQuery = '''
SELECT mi.id, mi.media_type_id, mi.vector_media_id, mi.title, mi.primary_creator,
       mi.cover_art_url, mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mi.youtube_id, mi.spotify_id, mi.created_at, mi.updated_at, mt.name as media_type
FROM media_items mi
JOIN media_types mt ON mi.media_type_id = mt.id
WHERE mi.id = ?;
''';

// Update media item
const String updateMediaItemQuery = '''
UPDATE media_items SET
  vector_media_id = ?, title = ?, primary_creator = ?, cover_art_url = ?,
  description = ?, wiki_url = ?, wikidata_id = ?, themes = ?, genres = ?, 
  youtube_id = ?, spotify_id = ?, updated_at = ?
WHERE id = ?;
''';

/// Recommendation Queries

// Insert a new recommendation
const String insertRecommendationQuery = '''
INSERT INTO recommendations (media_item_id, query, bot_reasoning, status_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?);
''';

// Update recommendation status
const String updateRecommendationStatusQuery = '''
UPDATE recommendations 
SET status_id = (SELECT id FROM recommendation_status WHERE name = ?), updated_at = ?
WHERE id = ?;
''';

// Get recommendation by ID
const String getRecommendationByIdQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE r.id = ?;
''';

// Get pending recommendations not in watchlist
const String getPendingRecommendationsNotInWatchlistQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
LEFT JOIN watchlist w ON mi.id = w.media_item_id
WHERE mt.name = ? AND rs.name = 'pending' AND w.media_item_id IS NULL
ORDER BY r.created_at DESC;
''';

// Get recommendations by status
const String getRecommendationsByStatusQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = ?
ORDER BY r.created_at DESC;
''';

// Count pending recommendations
const String countPendingRecommendationsQuery = '''
SELECT COUNT(*) as count
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = 'pending';
''';

// Delete recommendation
const String deleteRecommendationQuery = '''
DELETE FROM recommendations WHERE id = ?;
''';

/// Favorites Queries

// Add to favorites (works for both recommended and user-added items)
const String addToFavoritesQuery = '''
INSERT OR IGNORE INTO favorites (media_item_id, created_at) VALUES (?, ?);
''';

// Remove from favorites
const String removeFromFavoritesQuery = '''
DELETE FROM favorites WHERE media_item_id = ?;
''';

// Check if in favorites
const String isInFavoritesQuery = '''
SELECT COUNT(*) as count FROM favorites WHERE media_item_id = ?;
''';

// Get favorites for a media type (includes both recommended and user-added)
const String getFavoritesQuery = '''
SELECT f.id, f.created_at as favorited_at,
       mi.id as media_item_id, mi.vector_media_id, mi.title, mi.primary_creator,
       mi.cover_art_url, mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type,
       r.id as recommendation_id, r.query, r.bot_reasoning
FROM favorites f
JOIN media_items mi ON f.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
LEFT JOIN recommendations r ON mi.id = r.media_item_id
WHERE mt.name = ?
ORDER BY f.created_at DESC;
''';

/// Watchlist Queries

// Add to watchlist (works for both recommended and user-added items)
const String addToWatchlistQuery = '''
INSERT OR IGNORE INTO watchlist (media_item_id, created_at) VALUES (?, ?);
''';

// Remove from watchlist
const String removeFromWatchlistQuery = '''
DELETE FROM watchlist WHERE media_item_id = ?;
''';

// Check if in watchlist
const String isInWatchlistQuery = '''
SELECT COUNT(*) as count FROM watchlist WHERE media_item_id = ?;
''';

// Get watchlist for a media type (includes both recommended and user-added)
const String getWatchlistQuery = '''
SELECT w.id, w.created_at as watchlist_added_at,
       mi.id as media_item_id, mi.vector_media_id, mi.title, mi.primary_creator,
       mi.cover_art_url, mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type,
       r.id as recommendation_id, r.query, r.bot_reasoning
FROM watchlist w
JOIN media_items mi ON w.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
LEFT JOIN recommendations r ON mi.id = r.media_item_id
WHERE mt.name = ?
ORDER BY w.created_at DESC;
''';

// Move from watchlist to favorites
const String moveFromWatchlistToFavoritesQuery = '''
INSERT OR IGNORE INTO favorites (media_item_id, created_at)
SELECT media_item_id, ? FROM watchlist WHERE media_item_id = ?;

DELETE FROM watchlist WHERE media_item_id = ?;
''';

/// Advanced Behavioral Queries (for LLM learning)

// Get liked recommendations for behavioral analysis
const String getLikedRecommendationsQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = 'liked'
ORDER BY r.updated_at DESC;
''';

// Get disliked recommendations for behavioral analysis
const String getDislikedRecommendationsQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = 'disliked'
ORDER BY r.updated_at DESC;
''';

// Note: getFavoritedRecommendationsQuery and getWatchlistedRecommendationsQuery have been removed
// Use getAllFavoritesQuery and getWatchlistItemsQuery instead, which work with the normalized schema

// Get skipped recommendations for behavioral analysis
const String getSkippedRecommendationsQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning, rs.name as status,
       r.created_at, r.updated_at,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = 'skipped'
ORDER BY r.updated_at DESC;
''';

// Get user preference summary for behavioral analysis
const String getUserPreferenceSummaryQuery = '''
SELECT 
  rs.name as status,
  COUNT(*) as count,
  GROUP_CONCAT(DISTINCT mi.themes) as all_themes,
  GROUP_CONCAT(DISTINCT mi.primary_creator) as all_artists
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name IN ('liked', 'disliked', 'added')
GROUP BY rs.name;
''';

/// Media Metadata Queries

// Insert media metadata
const String insertMediaMetadataQuery = '''
INSERT OR REPLACE INTO media_metadata (media_item_id, key, value) 
VALUES (?, ?, ?);
''';

// Get media metadata
const String getMediaMetadataQuery = '''
SELECT key, value 
FROM media_metadata 
WHERE media_item_id = ?;
''';

// Get specific metadata value
const String getMediaMetadataValueQuery = '''
SELECT value 
FROM media_metadata 
WHERE media_item_id = ? AND key = ?;
''';

// Delete media metadata
const String deleteMediaMetadataQuery = '''
DELETE FROM media_metadata WHERE media_item_id = ?;
''';

// Get media items with specific metadata
const String getMediaItemsByMetadataQuery = '''
SELECT DISTINCT mi.id, mi.vector_media_id, mi.title, mi.primary_creator,
       mi.cover_art_url, mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type, mi.created_at, mi.updated_at
FROM media_items mi
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN media_metadata mm ON mi.id = mm.media_item_id
WHERE mt.name = ? AND mm.key = ? AND mm.value = ?
ORDER BY mi.title ASC;
''';

/// Search Queries

// Search media items by title or creator
const String searchMediaItemsQuery = '''
SELECT mi.id as media_item_id, mi.vector_media_id, mi.title, mi.primary_creator,
       mi.cover_art_url, mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type, mi.created_at, mi.updated_at
FROM media_items mi
JOIN media_types mt ON mi.media_type_id = mt.id
WHERE mt.name = ? AND (mi.title LIKE ? OR mi.primary_creator LIKE ?)
ORDER BY mi.title ASC;
''';

/// Legacy Compatibility Queries
/// These maintain compatibility with existing code during migration

// Get media suggestion by ID (legacy compatibility)
const String getMediaSuggestionByIdQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type, rs.name as status,
       r.created_at, r.updated_at
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE r.id = ?;
''';

// Insert media suggestion (legacy compatibility)
const String insertMediaSuggestionQuery = '''
INSERT INTO recommendations (
  media_item_id, query, bot_reasoning, status_id, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?);
''';

// Update media suggestion status (legacy compatibility)
const String updateMediaSuggestionStatusQuery = '''
UPDATE recommendations 
SET status_id = (SELECT id FROM recommendation_status WHERE name = ?), updated_at = ?
WHERE id = ?;
''';

// Delete media suggestion (legacy compatibility)
const String deleteMediaSuggestionQuery = '''
DELETE FROM recommendations WHERE id = ?;
''';

// Count pending media suggestions (legacy compatibility)
const String countPendingMediaSuggestionsQuery = '''
SELECT COUNT(*) as count
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ? AND rs.name = 'pending';
''';

// Get pending suggestions not in watchlist (legacy compatibility)
const String getPendingSuggestionsNotInWatchlistQuery = '''
SELECT r.id, r.media_item_id, r.query, r.bot_reasoning,
       mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
       mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
       mt.name as media_type, rs.name as status,
       r.created_at, r.updated_at
FROM recommendations r
JOIN media_items mi ON r.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
JOIN recommendation_status rs ON r.status_id = rs.id
LEFT JOIN watchlist w ON mi.id = w.media_item_id
LEFT JOIN favorites f ON mi.id = f.media_item_id
WHERE mt.name = ? AND rs.name = 'pending' AND w.media_item_id IS NULL AND f.media_item_id IS NULL
ORDER BY r.created_at DESC;
''';

// Get watchlist items (legacy compatibility - simplified without negative IDs)
const String getWatchlistItemsQuery = '''
SELECT 
  COALESCE(r.id, mi.id) as id, -- Use recommendation ID if exists, otherwise media_item_id
  mi.id as media_item_id, 
  COALESCE(r.query, 'User Added') as query, 
  COALESCE(r.bot_reasoning, 'Added from search') as bot_reasoning,
  mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
  mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
  mt.name as media_type, 
  COALESCE(rs.name, 'added') as status,
  COALESCE(r.created_at, w.created_at) as created_at, 
  COALESCE(r.updated_at, w.created_at) as updated_at, 
  w.created_at as watchlist_added_at
FROM watchlist w
JOIN media_items mi ON w.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
LEFT JOIN recommendations r ON mi.id = r.media_item_id AND r.id = (
  SELECT MAX(r2.id) FROM recommendations r2 WHERE r2.media_item_id = mi.id
)
LEFT JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ?
GROUP BY mi.id
ORDER BY w.created_at DESC;
''';

// Get favorites items (legacy compatibility)
const String getFavoritesItemsQuery = '''
SELECT 
  COALESCE(r.id, mi.id) as id, -- Use recommendation ID if exists, otherwise media_item_id
  mi.id as media_item_id, 
  COALESCE(r.query, 'User Added') as query, 
  COALESCE(r.bot_reasoning, 'Added from search') as bot_reasoning,
  mi.vector_media_id, mi.title, mi.primary_creator, mi.cover_art_url,
  mi.description, mi.wiki_url, mi.wikidata_id, mi.themes, mi.genres,
  mt.name as media_type, 
  COALESCE(rs.name, 'added') as status,
  COALESCE(r.created_at, f.created_at) as created_at, 
  COALESCE(r.updated_at, f.created_at) as updated_at, 
  f.created_at as favorited_at
FROM favorites f
JOIN media_items mi ON f.media_item_id = mi.id
JOIN media_types mt ON mi.media_type_id = mt.id
LEFT JOIN recommendations r ON mi.id = r.media_item_id
LEFT JOIN recommendation_status rs ON r.status_id = rs.id
WHERE mt.name = ?
ORDER BY f.created_at DESC;
''';